# Generated by Django 3.0.4 on 2020-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200401_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readNum',
            field=models.IntegerField(default=0),
        ),
    ]
