# Generated by Django 3.0.4 on 2020-04-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200401_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='readNum',
        ),
    ]
